include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/**, lib/**.graphql.dart, lib/**.g.dart ]
  errors:
    deprecated_member_use_from_same_package: ignore
linter:
  rules:
    - require_trailing_commas: true